---
title: "Untitled"
author: "Mario"
date: "13/12/2022"
output: html_document
---

```{r}
# Clean and load packages ----

packages.to.use <- c("tictoc", "raster", "devtools", "VoCC","rgeos",
                     "rasterVis","gridExtra","doParallel","foreach",
                     "scales","data.table","mapplots","repmis","sf",
                     "rnaturalearth", "rnaturalearthdata", "viridis", 
                     "tidyverse","rgdal", "writexl","ggpubr", "diffeR", 
                     "readxl",  "NicheMapR", "microclima", "rgdal","sf","magrittr",
                     "tidyverse","tmap",  "lubridate", "PupillometryR")

packages.to.use <- unique(packages.to.use)

for(package in packages.to.use) {
  print(package)
  if( ! package %in% rownames(installed.packages()) ) { install.packages(package ) }
  if( ! package %in% rownames(installed.packages()) ) { stop("Error on package instalation") }
  suppressWarnings( library(package, character.only = TRUE) )
}

# Transects------


data <- readOGR("B:/MARIPOSAS/TRANSECTOS_MICROCLIMA/transectos_89N.shp")

scrub <- c("3Pat","11Pat","51Cer","64Hir","77Col","87Mal","89Col","96Cab","103Mal","105Ver")

# scrub <- c("3Pat","11Pat","51Cer","64Hir","77Col","87Mal","89Col","96Cab","103Mal","105Ver","111Hor","112Fle","113Pio","121Mal","122Bol",
#            "104Naj","106Tir","108Naj","110Val","114Bai","117Val","12Rio","20Tom","28Val","34Val","36Pue","37Ang",
#            "42Can","46Ped","48Cam","50Can","60Ace","67Mon","71Leo","73Ace","75Mat","78Mon","86Pen","90Cer","94Mon")


transect <- subset(data, data$CODIGO %in% scrub)


## Get the centroids ----
transect_centr <- gCentroid(transect, byid = TRUE)
transect_centr <- SpatialPointsDataFrame(transect_centr, data = transect@data)



## Get lat and long ----

lat_long <- coordinates(spTransform(transect_centr, CRS("+proj=longlat + datum=WGS84")))
lat_comp <- lat_long[,2]
long_comp <- lat_long[,1]

## Get dates ----
##### 2003-2005 2015-2017
fi <- seq(as.Date("2003-01-01"), length=36, by="month")
ff <- seq(as.Date("2003-02-01"), length=36, by="month")-1


f_inicio <- data.frame(fecha_mal = fi) %>% 
  separate(fecha_mal, into = c("dia", "mes", "a単o")) %>%
  mutate(fecha_bien = paste(a単o, mes, dia, sep = "/")) %>%
  dplyr::select(fecha_bien) %>% 
  filter(grepl("/03/|/04/|/05/|/06/|/07/|/08/", fecha_bien))


f_fin <- data.frame(fecha_mal = ff) %>% 
  separate(fecha_mal, into = c("dia", "mes", "a単o")) %>%
  mutate(fecha_bien = paste(a単o, mes, dia, sep = "/")) %>%
  dplyr::select(fecha_bien)%>% 
  filter(grepl("/03/|/04/|/05/|/06/|/07/|/08/", fecha_bien))
```

```{r, results = "hide", message = FALSE, warning = FALSE}
## Run microclima ----

tic("Tiempo ejecucion total: ") 

invisible(for (j in 1:length(lat_comp)){
  lat <- lat_comp[j]
  long <- long_comp[j]
  mdt <- microclima::get_dem(lat = lat, long = long, resolution = 30)
  for (i in 1:nrow(f_fin)){
    temp <- runauto(mdt,
                    f_inicio[i,], f_fin[i,], 
                    hgt = 0.1, 
                    l = NA, x = NA,
                    coastal = FALSE,
                    habitat = 7, ######## MODIFICAR #########
                    plot.progress = FALSE, save.memory = FALSE)
    tmax <- temp$tmax
    tmin <-temp$tmin
    tmed <- temp$tmean
    writeRaster(tmax, paste0("B:/MARIPOSAS/TRANSECTOS_MICROCLIMA/MICROCLIMA/2003_2005/TMAX/tmax_", scrub[j], "_", gsub("/","_", substr(f_inicio[i,], 4,10)),".tif"))
    writeRaster(tmin, paste0("B:/MARIPOSAS/TRANSECTOS_MICROCLIMA/MICROCLIMA/2003_2005/TMIN/tmin_", scrub[j], "_", gsub("/","_", substr(f_inicio[i,], 4,10)),".tif"))
    writeRaster(tmed, paste0("B:/MARIPOSAS/TRANSECTOS_MICROCLIMA/MICROCLIMA/2003_2005/TMED/tmed_", scrub[j], "_", gsub("/","_", substr(f_inicio[i,], 4,10)),".tif"))
  }
})

toc()

#number                         descriptor
# 1        Evergreen needleleaf forest
# 2         Evergreen Broadleaf forest
# 3        Deciduous needleleaf forest
# 4         Deciduous broadleaf forest
# 5                       Mixed forest
# 6                  Closed shrublands
# 7                    Open shrublands
# 8                     Woody savannas
# 9                           Savannas
#10                   Short grasslands
#11                    Tall grasslands
#12                 Permanent wetlands
#13                          Croplands
#14                 Urban and built-up
#15 Cropland/Natural vegetation mosaic
#16       Barren or sparsely vegetated
#17                         Open water

##--------------------------------------------------------------------------------------------------------------------------------------

```
